function [UD] = UD_setup(info)

%--------------------------------------------------------------------------
UD = PAL_AMUD_setupUD('up',1,'down',1,...
        'stepSizeDown',info.UD_step_size_down,...
        'stepSizeUp',info.UD_step_size_up,...
        'stopCriterion',info.UD_stop_criterion,...
        'stopRule',info.UD_stop_rule,...
        'startValue',info.UD_start_value,...
        'xMax',info.UD_xmax,...
        'xMin',info.UD_xmin);
end